행벡터 생성

In [1]:
import numpy as np
age = np.array([60,70,12])
age

array([60, 70, 12])

열벡터 생성

In [2]:
age = np.array([[60],[70],[12]])
age

array([[60],
       [70],
       [12]])

행렬 생성

In [3]:
age = np.arange(1,6)
age

array([1, 2, 3, 4, 5])

배열 원소 0, 1, 임의의 수로 채우기

In [4]:
age = np.zeros((2,3))
age

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
age_one = np.ones(5)
age_one

array([1., 1., 1., 1., 1.])

In [6]:
age_random = np.random.rand(2,2)
age_random

array([[0.41070693, 0.70813962],
       [0.53339246, 0.75421424]])

배열 사칙연산 (더하기, add( ) )

In [7]:
temp1 = np.array([[1,2],[3,4]])
temp2 = np.array([[1,1],[1,1]])
temp1 + temp2

array([[2, 3],
       [4, 5]])

In [8]:
temp1 = np.array([[1,2],[3,4]])
temp2 = np.array([[1,1],[1,1]])
np.add(temp1, temp2)

array([[2, 3],
       [4, 5]])

배열 사칙연산 (뺄셈, subtract( ) )

In [9]:
temp1 = np.array([[1,2],[3,4]])
temp2 = np.array([[1,1],[1,1]])
temp1 - temp2

array([[0, 1],
       [2, 3]])

In [10]:
temp1 = np.array([[1,2],[3,4]])
temp2 = np.array([[1,1],[1,1]])
np.subtract(temp1, temp2)

array([[0, 1],
       [2, 3]])

배열 사칙연산 (곱셈, multiply( ) )

In [11]:
temp1 = np.array([[1,2],[3,4]])
temp2 = np.array([[2,2],[2,2]])
temp1 * temp2

array([[2, 4],
       [6, 8]])

In [12]:
temp1 = np.array([[1,2],[3,4]])
temp2 = np.array([[2,2],[2,2]])
np.multiply(temp1, temp2)

array([[2, 4],
       [6, 8]])

배열 사칙연산 (나누기, divide( ) )

In [13]:
temp1 = np.array([[1,2],[3,4]])
temp2 = np.array([[2,2],[2,2]])
temp1 / temp2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [14]:
temp1 = np.array([[1,2],[3,4]])
temp2 = np.array([[2,2],[2,2]])
np.divide(temp1, temp2)

array([[0.5, 1. ],
       [1.5, 2. ]])

행렬의 곱 (결과는 스칼라)

In [15]:
temp1 = np.array([[1,2,3]])
temp2 = np.array([[4],[5],[6]])
temp1.dot(temp2)

array([[32]])

행렬의 곱 (결과는 행렬)

In [16]:
temp1 = np.array([[1,2,3],[4,5,6]])
temp2 = np.array([[1,2],[3,4],[5,6]])
temp1.dot(temp2)

array([[22, 28],
       [49, 64]])

통계 합수 sum( )

In [17]:
temp1 = np.array([[1,2,3], [4,5,6]])
temp1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
temp1 = np.array([[1,2,3], [4,5,6]])
np.sum(temp1)

21

In [19]:
temp1 = np.array([[1,2,3], [4,5,6]])
np.sum(temp1, axis = 0)
# axis = 0
# 행의 원소 합계

array([5, 7, 9])

In [20]:
temp1 = np.array([[1,2,3], [4,5,6]])
np.sum(temp1, axis = 1)
# axis = 1
# 열의 원소 합계

array([ 6, 15])

In [21]:
temp1 = np.array([[1,2,3], [4,5,6]])
np.mean(temp1, axis = 0)
# mean : 평균

array([2.5, 3.5, 4.5])

In [22]:
temp1 = np.array([[1,2,3], [4,5,6]])
np.median(temp1)
# median : 중앙값

3.5

In [23]:
temp1 = np.array([[1,2,3], [4,5,6],[7,8,10]])
np.median(temp1)
# median : 중앙값
# 원소의 개수가 짝수일때는 중앙값이 2개가 될 수 있으며 이 2개의 평균값을 출력

5.0

통계 함수 최대값 : max( )

In [24]:
temp1 = np.array([[1,2,3], [4,5,6]])
np.max(temp1)

6

통계 함수 최소값 : min( )

In [25]:
temp1 = np.array([[1,2,3], [4,5,6]])
np.min(temp1)

1

최대/최소값 인덱스 (위치를 반환)

In [26]:
temp1 = np.array([[1,2,3], [4,5,6]])
np.argmax(temp1)

5

In [27]:
temp1 = np.array([[1,2,3], [4,5,6]])
np.argmin(temp1)

0

통계 함수 최소값 : 분산 / 표준편차

    - 표준편차 개념 : 평균에 대한 오차
        실제 데이터 값이 평균을 기준으로 할때 얼마나 들쑥날쑥하냐를 나타내는 것
        평균이 m이고, 표준편차가 3이라고 할때 실제 값은 m±3

    - 분산 (Variance) : 편차의 제곱의 합
        원래의 값에서 평균을 뺀 값인데, 편차는 +가 될 수도 있고, -가 될 수도 있다
        그래서 음수를 양수화하기 위해 제곱을 해서 합친 값이 분산이다.
        
    - 표준편차 : 분산에 루트를 씌운 값

배열 조건 검색 any( )

    - 배열에 특정 조건을 만족하는 원소가 1개 이상이면 True, 아니면 False

In [28]:
obj = np.array([[1.9, -0.6, -0.7, 0.55, -0.9]
               ,[-0.14, 0.04, -0.6, -1.4, 0.9]
               ,[0.1, 0.56, -0.78, 0.27, 0.6]])
np.any(obj > 0)

True

배열 조건 검색 all( )

    - 배열에 특정 조건을 모든 원소가 만족하면 True, 아니면 False

In [29]:
obj = np.array([[1.9, -0.6, -0.7, 0.55, -0.9]
               ,[-0.14, 0.04, -0.6, -1.4, 0.9]
               ,[0.1, 0.56, -0.78, 0.27, 0.6]])
np.all(obj > 0)

False

배열 조건 검색 where( )

    - 배열에 특정 조건을 만족하는 것과 그렇지 않는 것에 대한 서로 다른 결과를 출력

In [30]:
obj = np.array([[1.9, -0.6, -0.7, 0.55, -0.9]
               ,[-0.14, 0.04, -0.6, -1.4, 0.9]
               ,[0.1, 0.56, -0.78, 0.27, 0.6]])
np.where(obj > 0, obj, 0)
# 0 보다 크면 원소값 그대로 사용하고 0 이하면 0 으로 설정

array([[1.9 , 0.  , 0.  , 0.55, 0.  ],
       [0.  , 0.04, 0.  , 0.  , 0.9 ],
       [0.1 , 0.56, 0.  , 0.27, 0.6 ]])

배열의 모양 변경 (차원 변경)

In [31]:
obj = np.array([[1,2,3,]])
obj

array([[1, 2, 3]])

In [32]:
obj = np.array([[1,2,3,]])
obj.reshape(3,1)

array([[1],
       [2],
       [3]])

In [33]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

브로드캐스팅 : 일정 조건만 맞으면 서로 다른 모양의 배열끼리 연산할 수 있도록 하는 기능

    - 한 배열의 차원이 1일때
    - 첫 번째 배열의 행의 개수와 두번째 배열의 열의 개수가 같을 때

In [35]:
# 배열 + 스칼라 값
from numpy.core.multiarray import array
obj = array([[1,2,3]])
obj_result = obj + 1
obj_result

array([[2, 3, 4]])

In [36]:
# 배열 (3,3) + 배열 (1,3) -> 뒷 배열의 행이 1이므로 브로드캐스팅 가능
obj = np.arange(9).reshape(3,3) + np.arange(3)
obj

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [37]:
# 배열 (3,1) + 배열 (1,3) -> 첫 번째 배열의 행의 개수와 두 번째 배열의 열의 개수가 같을 때
obj = np.array([[1,2,3]])
obj.reshape(3,1) + np.arange(3)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [38]:
# 문제풀이
obj = np.array([[1.923, -0.612, -0.742, 0.555, -0.942]
               ,[-0.1412, 0.0486, -0.636, -1.464, 0.934]
               ,[0.123, 0.5653, -0.7844, 0.2716, 0.686]
               ,[1.145, 0.1265, 0.5236, -1.253, 1.343]
               ,[0.5643, -0.4342, 0.8648, 1.344, -254]])
obj2 = np.where(obj > 0.5, obj, 0)
obj_result = obj2 * 10
obj_result = np.round(obj_result, 2)
obj_result

array([[19.23,  0.  ,  0.  ,  5.55,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  9.34],
       [ 0.  ,  5.65,  0.  ,  0.  ,  6.86],
       [11.45,  0.  ,  5.24,  0.  , 13.43],
       [ 5.64,  0.  ,  8.65, 13.44,  0.  ]])

In [39]:
# 문제풀이
arr = np.random.random((5,5))
arr[arr < 0.5] = 0
arr *= 10
arr = np.round(arr, 2)
arr

array([[6.64, 7.92, 0.  , 0.  , 6.7 ],
       [9.01, 0.  , 8.69, 7.32, 0.  ],
       [0.  , 8.28, 6.7 , 0.  , 0.  ],
       [0.  , 7.04, 5.24, 0.  , 9.39],
       [0.  , 6.32, 5.37, 0.  , 0.  ]])